### ISSUE TITLE
Move source files from `sfd` to `sfdir`

### ISSUE THREAD

**Issue by nclm** [ms-studio/karmilla#21]
Hi!

I just discovered Fontforge has a ‘save as folder’ feature where the `sfd` file is cut into files for every individual glyphs plus a metadata file, in a way very similar of what an `ufo` do.

I believe it would be a format more adapted for working on Git? So we can see exactly what glyphs/files are edited at each commit, only pull&push what is changing, and be sure not to alter anything that shouldn’t by mistake. It’s more flexible.

If you’re okay with this, I’m doing it just after ß (#20) is merged!

**Comment by raphaelbastide** [comment]
As ufo is universal, why not using it instead of sfdir ?

**Comment by nclm** [comment]
Yes, I was replying to the other thread at the same time :) #17

**Comment by ms-studio** [comment]
Ok with me!    
Could one of you:

1. Transform the source into UFO format (fixing #17).
2. pull in the first draft of ß glyph (#20) by @elpoto, finally fixing #8.

Btw, that pull request for some reason is making changes to all files of the repo. I would prefer for clarity to just import the new glyph.

**Comment by davelab6** [comment]
UFO support should now be pretty solid, if you find bugs please file them :)

**Comment by nclm** [comment]
(moving to UFO instead)
