### ISSUE TITLE
French single quotes

### ISSUE THREAD

**Issue by ogilv** [ms-studio/karmilla#24]
Since the regular french quotation marks («guillemets») have been added already, single guillemets would be a simple, but welcome addition! They're primarily used when there is a quote nested within a quote:

>  «The word ‹guillemet› is new to me», Karla admitted.

**Comment by nclm** [comment]
Good idea. I just added these, feel free to try them!

**Comment by nclm** [comment]
By the way, weirdly, I never really thought about these ones. While I make use of both ‘’ and “” in English, I’m only using «» in French. As soon as I find a way to input them from the keyboard, they’re adopted! Thanks :)

**Comment by ms-studio** [comment]
Awesome! Thanks @nclm for the quick update!
