### ISSUE TITLE
Bold font in v.013 not working

### ISSUE THREAD

**Issue by ogilv** [ms-studio/karmilla#27]
Thank you @nclm for the quick fix of #24 – and the added «ß», too, will be a welcome addition for many! Karmilla is a gem.

I have a problem with the bold font in v.013, though. On Mac OS X 10.10.5, I don't see bold it in the font selection menu, and in quick view, it displays the regular weight instead. With v.012, I experienced none of these issues…

**Comment by nclm** [comment]
You’re right, I probably got tangled with my files yesterday (working on a new computer) and exported the Regular twice, once as Regular, once as Bold. I’m fixing this later today :) Sorry!

**Comment by nclm** [comment]
It should work now! Sorry again for the mixing up 🌀
