### ISSUE TITLE
Create missing characters for the Norwegian language (Æ and Ø)

### ISSUE THREAD

**Issue by lokeland** [ms-studio/karmilla#29]
See https://en.wikipedia.org/wiki/%C3%98 and https://en.wikipedia.org/wiki/%C3%86.
The Æ does exist in the bold version though.

**Comment by ms-studio** [comment]
Working on it! @lokeland, can you please check out the Karmilla-Regular-014.ttf file at https://github.com/ms-studio/karmilla/tree/master/ttf and tell me if the ø and Ø look good?

**Comment by lokeland** [comment]
Wow. It looks really good!

**Comment by ms-studio** [comment]
Done! I went finally for a more squarish shape, similar to fonts such as Akkurat, Arial, Droid Sans...

<img width="1086" alt="screen shot 2015-09-18 at 22 46 09" src="https://cloud.githubusercontent.com/assets/241637/9971628/9fdeb4c0-5e5d-11e5-9877-d3f151831e65.png">

**Comment by madspalsrud** [comment]
Hello!
I see that æ+ø is added to the file but when I write those letters in any program, it does not show in the regular! Only the bold! Please help? :) Thank you!
