### ISSUE TITLE
submit font to google webfonts

### ISSUE THREAD

**Issue by Eduruiz** [ms-studio/karmilla#31]
the font will be submitted to google web fonts? I have a layout with karla and the lack of the "ç" will make me give up of the font, but if I can use karmilla from google fonts it will be the one. :)

here's a [link to font submission form](https://docs.google.com/forms/d/1w2JOnVv_Vfcg1H_nploj1FRz4LcFsLaFmFkEj50PyW4/viewform).

**Comment by ms-studio** [comment]
Indeed, we could think about that ... Wondering what's the Google Fonts policy about derivative fonts – a question for @davelab6.

If you don't want to self-host the fonts, you could still put this one-liner into your website, and load them from Github:

`<link rel="stylesheet" href="https://raw.githubusercontent.com/ms-studio/karmilla/27ea4e4cb11962d3a66cb4b350bdfabe393b4ae5/webfontkit/karmilla-015/stylesheet.css" type="text/css" />`

**Comment by davelab6** [comment]
Maybe can get Jonny to take this upstream.

**Comment by andrewshadura** [comment]
He mentioned on Twitter that he plans releasing an update: https://twitter.com/jonpinhorn_type/status/685465411777904640

**Comment by pietrogregorini** [comment]
@jonpinhorn Any news about Karla updates?

**Comment by StefanPeev** [comment]
I offered to Jonny my efforts for adding Cyrillic (both traditional one as well as modern forms of Bulgarian Cyrillic and the local forms of Serbian and Macedonian). He answered that the idea is a good one but I'm still waiting him to go home from a Holidays :) . Meanwhile the same could be done for Karmilla if you want.

**Comment by andrewshadura** [comment]
I think it would be great if Karmilla supported Cyrillic! I think I could help shape symbols, as my native languages both use Cyrillic.

**Comment by StefanPeev** [comment]
Here is my initial offer for Karla. So I could transform the glyphs to match the Karmilla's glyph forms.

![karla_01](https://cloud.githubusercontent.com/assets/12949369/22552666/8f6a28b8-e962-11e6-9de4-7dd58e6dd04c.jpg)

**Comment by andrewshadura** [comment]
Looks fine… but I think the Ч/ч is a bit too Bulgarian in the Russian version. Have you thought about making the the connecting curve a bar curved to the corner, not a half-loop, or at least less curved in its horizontal part?

**Comment by andrewshadura** [comment]
Especially in the lowercase version. In fact, I think, Bulgarian could also benefit from it… But I don't know much about Bulgarian typing traditions, so I may be wrong.

**Comment by andrewshadura** [comment]
One more idea: what do you think about adding a hook to the capital У similar to the one lowercase у has, but possibly a bit smaller? I think that change could apply to both versions.

**Comment by andrewshadura** [comment]
Is it just me or the resulting Cyrillic text looks a bit more dense than the corresponding Latin text?

**Comment by StefanPeev** [comment]
@andrewshadura Thank you for your commets! OK, it is still a draft version – big enough, but not finalized. If the @ms-studio would like to include Cyrillic in Karmilla, I'll start from the draft and will work in this direction – loading the source variants (as FontForge files and UFO files) here.

**Comment by ms-studio** [comment]
@StefanPeev Thank you for your proposal! Sure, I'm happy to include the cyrillics in Karmilla. Can you do a pull request?

**Comment by StefanPeev** [comment]
@ms-studio Well, I try to create a pull request but the results are always comparing of branches. Some help please.

**Comment by andrewshadura** [comment]
@StefanPeev, your branch `cyrillic` doesn't have any new commits at the moment. Probably, you forgot to push it.

**Comment by StefanPeev** [comment]
And what I need to change now?

**Comment by andrewshadura** [comment]
What does `git log master..cyrillic` say on your local machine?

**Comment by StefanPeev** [comment]
@andrewshadura I deleted this branch with the idea to start from the begining. Will you give me some help?

**Comment by andrewshadura** [comment]
Just `git checkout` your new branch, `git add` stuff, `git commit` it and `git push` the branch. There’s a bunch of tutorials on the internet on the details, but feel free to ask here if you run into troubles.

**Comment by StefanPeev** [comment]
@andrewshadura So, I've a fork of the repository Karmila on my profile. So the next step is...

**Comment by andrewshadura** [comment]
Have you cloned it on your local machine?

**Comment by StefanPeev** [comment]
No, I work directly online. What do you mean to clone up to my local machine?

**Comment by andrewshadura** [comment]
No, you can't do this on-line fully. On-line editing is for trivial changes only, which this isn't.

**Comment by andrewshadura** [comment]
You need to install Git locally and add things there.

I understand Git is very tricky and difficult to understand for new users (and I quite dislike its over-complicated user interface myself), but please try to solve trivial issues yourself with the help of tutorials like [this](https://git-scm.com/docs/gittutorial), [this one](http://rogerdudler.github.io/git-guide/) or [GitHub's one](https://try.github.io/).

I'm happy to help you with the rest, but please try to follow the steps described there.

**Comment by StefanPeev** [comment]
OK! I'll look at the tutorials. Thank you!

**Comment by StefanPeev** [comment]
@andrewshadura I hope that pull request is ready now...

**Comment by andrewshadura** [comment]
@StefanPeev, I don't understand… there's only a picture, no actual font data. Have you committed wrong files?

**Comment by StefanPeev** [comment]
No, I only committed the picture - just as a begining :)

**Comment by StefanPeev** [comment]
I'm now changing my Karla project to Karmilla project - so, I need a little time.

**Comment by andrewshadura** [comment]
There's no need to submit the picture. But there's no need to hurry.
Just take your time to prepare a branch with all changes you want to submit, and when it's ready, update the pull request.

**Comment by andrewshadura** [comment]
In fact, every time you push the branch to GitHub, your pull request will update automatically. So if you want to keep Karmilla project up-to-date about your work, just push your branch regularly.

**Comment by andrewshadura** [comment]
At the end your pull request will look like [this](https://github.com/ms-studio/karmilla/pull/32), or [this](https://github.com/ms-studio/karmilla/pull/33), or [that](https://github.com/ms-studio/karmilla/pull/14).

**Comment by StefanPeev** [comment]
OK, but I'll really need a time, because there are differences between Karla and Karmilla and I must carefully check them and to change my project to Karmilla.

**Comment by andrewshadura** [comment]
Sure. Don't worry, just do your work and submit it when it's ready.

**Comment by davelab6** [comment]
cc @alexeiva

**Comment by elbotho** [comment]
as per my suggestion and they very nice response karmilla is now on fontsquirrel:
https://www.fontsquirrel.com/fonts/karmilla

It's a start I figured ;)
