### ISSUE TITLE
Fix vertical metrics adjustment in webfonts

### ISSUE THREAD

**Issue by selfagency** [ms-studio/karmilla#34]
i love this font and really wanted to use it in a project of mine but unfortunately the baseline seems to be way higher than it ought to be and the letter spacing is far too wide. here are a couple of screencaps that show the baseline shift. that gap beneath the characters shouldn't be there. for reference, karla's baseline is flush with the bottom of the selection.

![screenshot 2016-01-27 17 56 44](https://cloud.githubusercontent.com/assets/2541728/12725392/7b17dba6-c8e0-11e5-9fbd-cd7d0ead9579.png)
![screenshot 2016-01-27 17 56 07](https://cloud.githubusercontent.com/assets/2541728/12725393/7b1aa8ea-c8e0-11e5-8daf-6caa206f4d73.png)

**Comment by nclm** [comment]
Hi!

Indeed for the line height, I wonder how we lost that from Karla. Let’s check if there’s a simple option to adjust it in Fontforge. For now, you can change the default _leading_ in your layout software or edit the `line-height` in your CSS.

As for the letter spacing, the issue is already open (#23), and there’s also a discussion about this on #22. Here also, modifying the _tracking_ or editing `letter-spacing` is the solution for now.

**Comment by selfagency** [comment]
@nclm the second image above is what happens when i apply a line height to my type which has a transparent background

**Comment by ms-studio** [comment]
Interesting! In my view, the generous line height and spacing of Karla / Karmilla are a design decision. When I compare Karmilla v.15 with the original Karla font, the line height and spacing are the same. Here's a screenshot of Karla, Karmilla and Helvetica side by side:

<img width="798" alt="karla-karmilla-helvetica" src="https://cloud.githubusercontent.com/assets/241637/12729950/8cacf254-c929-11e5-8f4a-c67e05696a29.png">

Indeed for some projects, I have been wishing for tighter spacing and line height, but didn't have any problem setting this with CSS or the layout software, as @nclm says.

In what software are you encountering the unwanted overlay seen in the second image?

**Comment by selfagency** [comment]
i'm using it in a web design with a font-face kit and that extra height is what i'm getting in-browser.

**Comment by selfagency** [comment]
@nclm my guess how you lost the height is by adding height at the bottom to accommodate special characters, like ç. but that's just a guess b/c i haven't opened it in a font editor.

**Comment by jonpinhorn** [comment]
Hi guys,

Manuel is right; it was a design decision. Karla Latin was designed as the companion script to Karla Tamil, also available on Google Fonts. The unusual line spacing came about, in part, through experimentation with typesetting Latin and Tamil scripts together as well as attempts to make the design’s textures similar to each other.

Jonny Pinhorn

**Comment by selfagency** [comment]
the problem with that @jonpinhorn is that for those who want to use karla latin as a webfont on latin-only sites, the baseline shift causes typesetting consistency problems, like the offset text above. our publication uses english and spanish and thus i don't need line spacing parity with tamil. is it possible to create a subset for those trying to compliment asian scripts separate from the primary latin set?

**Comment by jonpinhorn** [comment]
At this moment I would suggest making modifications or a fork to Karmilla. Thanks.

**Comment by nclm** [comment]
If the desktop Karmilla has the same leading than Karla, then something is wrong in our webfonts. Try regenerating the webfonts with http://fontsquirrel.com/tools/webfont-generator with ‘no adjustment’ of vertical metrics (in ‘Expert’). I believe we mistakenly left the ‘auto-adjust’ on for the webfonts.

**Comment by selfagency** [comment]
that resolved it!

**Comment by nclm** [comment]
Great!
So that’s something to fix in Karmilla exported webfonts. Let’s use this bug for this.

**Comment by nclm** [comment]
It should now be fixed!

**Comment by selfagency** [comment]
👍
