### ISSUE TITLE
Add missing glyphs for Turkish (Ğ, ğ)

### ISSUE THREAD

**Issue by bahtiyarerden** [ms-studio/karmilla#36]
Hello can you add the 'ş' and 'ğ' letters to the collection?

Thank you

**Comment by nclm** [comment]
Hi Bahtiyar,
I opened the font source files to add them and they were both already there! :)
Are you using version 015?

**Comment by ms-studio** [comment]
I just checked – U+011e (Ğ), U+011f (ğ) are present in Regular, but missing in the Bold version.
