### ISSUE TITLE
Missing glyph in bold "ó" 

### ISSUE THREAD

**Issue by sofiamoya** [ms-studio/karmilla#41]
Bold version is missing "ó" glyph, a e i and u work just right:

<img width="250" alt="captura de pantalla 2017-03-02 a las 1 08 32 p m" src="https://cloud.githubusercontent.com/assets/3453526/23522672/7c73a7dc-ff49-11e6-9cfb-f5e671d46a03.png">

**Comment by ms-studio** [comment]
Hmm, that's weird. I don't see that issue, the ó appears to be present, both in the .ttf version (in the ttf folder) and the webfontkit.

Which font file did you use? 

I just produced an example here, using the webfontkit (version 16):
https://greyscalepress.com/glyph-test-a-e-i-o-u/

**Comment by ms-studio** [comment]
PS, a possible cause of error with accented characters : you can have different versions of ó – the normal one (that you obtain by typing it), and a "special" one, known as "combining characters" ... I mostly encounter them when copy-pasting from a PDF, or from a MacOSX filename.

Possibly, your ó is such a combined character, and this causes the display issue?

**Comment by sofiamoya** [comment]
@ms-studio sorry for the late reply, we realized that it works on web, and that's all we needed, i'm pretty sure you're right, it's my version of **o**, maybe because I was trying to use an spanish accent.

**Comment by ms-studio** [comment]
@sofiamoya thanks for confirming that it works :) can you share the link so we can see the font in use?
