### ISSUE TITLE
Tabular figures

### ISSUE THREAD

**Issue by cssobral2013** [ms-studio/karmilla#50]

**Comment by ms-studio** [comment]
Hi Cristiano,
are you planning to work on the tabular figures, that were recently talked about in issue #46 ?

**Comment by cssobral2013** [comment]
Yes. I'll review and see if It needs tweaking.

Em qua, 27 de mar de 2019 17:38, Manuel Schmalstieg <
notifications@github.com> escreveu:

**Comment by cssobral2013** [comment]
Anyway, apologize my fault, I Didn't search It before Opening issue.

**Comment by cssobral2013** [comment]
Meanwhile, It looks this issue can be closed, then.
