### ISSUE TITLE
Hungarian types are missing

### ISSUE THREAD

**Issue by eliquame** [ms-studio/karmilla#53]
Dear developer!

Could you help me? Your "extended" version and the google fonts version arent containt the hungarian accented letters. (Ő & Ű)

Thank you!

**Comment by andrewshadura** [comment]
@ms-studio, the Hungarian umlauts are there, but the combining character they include looks a bit non-bold. I could spend some time on emboldening it (but maybe in the evening), or maybe you could try too.
