### ISSUE TITLE
Unicode Range

### ISSUE THREAD

**Issue by ayuhito** [ms-studio/karmilla#59]
We've been supporting Karmilla at [Fontsource](https://github.com/fontsource/fontsource) for a while and I've been wondering if you could provide the values for the CSS unicode-range selector? That would be super useful for the project and users downstream.

Thanks!

**Comment by ms-studio** [comment]
Hi @DecliningLotus , could you give me some hints regarding how to proceed?

How to figure out the unicode-range?  
Where should this value be indicated?

**Comment by ayuhito** [comment]
Sorry, I don't think this is necessary anymore. Thanks for taking the time to respond!
